version: "3.9"

services:
  web:
    image: nginx:1.27-alpine
    container_name: randomhost
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro